server:
  port: 8090

short-link:
  domain: http://localhost:8090
  code-length: 7
  health-check:
    connect-timeout-millis: 2000
    request-timeout-millis: 3000
    batch-timeout-millis: 8000
    url-probe-pool-size: 16
    url-probe-queue-capacity: 64
    dns-resolver-pool-size: 4
    dns-resolver-queue-capacity: 64
